# Generated by Django 4.2.11 on 2024-05-10 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteid', models.AutoField(primary_key=True, serialize=False)),
                ('noteName', models.CharField(max_length=100)),
                ('noteDescription', models.TextField()),
                ('noteURL', models.URLField()),
                ('extension', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('cmsId', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pfpURL', models.URLField()),
                ('learningInstitution', models.CharField(max_length=100)),
                ('courseMajor', models.CharField(max_length=100)),
                ('interests', models.TextField()),
                ('savedNotes', models.TextField()),
                ('likedNotes', models.TextField()),
                ('following', models.TextField()),
                ('isCreator', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('noteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.note')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
