# Generated by Django 4.2.11 on 2024-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='departmentId',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='schoolId',
            field=models.AutoField(default=10000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
