# Generated by Django 4.2.11 on 2024-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='savedNote',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='UserProfileId',
            new_name='ProfileId',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likedNotes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='savedNotes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isLecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='isCreator',
            field=models.BooleanField(default=False),
        ),
    ]
