# Generated by Django 4.2.11 on 2024-05-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_department_delete_lecturer_delete_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pfpURL',
        ),
    ]
