# Generated by Django 4.2.11 on 2024-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_userprofileid_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ProfileId',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
