# Generated by Django 4.2.11 on 2024-05-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_pfpurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolId', models.AutoField(primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
