# Generated by Django 4.2.11 on 2024-05-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_id_userprofile_profileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='Department',
            field=models.OneToOneField(default=10000, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
    ]
