# Generated by Django 4.2.11 on 2024-05-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lecturer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
