# Generated by Django 4.2.11 on 2024-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institutionId', models.AutoField(primary_key=True, serialize=False)),
                ('institutionName', models.CharField(max_length=100, null=True)),
                ('institutionLocation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
