# Generated by Django 4.2.11 on 2024-05-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='learningInstitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
        ),
    ]
