# Generated by Django 4.2.11 on 2024-05-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lecturer_department_alter_lecturer_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ARId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resourceId', models.AutoField(primary_key=True, serialize=False)),
                ('resourceName', models.CharField(max_length=100)),
                ('resourceDescription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='savedNote',
        ),
        migrations.AddField(
            model_name='academicresources',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resources'),
        ),
        migrations.AddField(
            model_name='academicresources',
            name='uploadedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedBy', to='core.userprofile'),
        ),
    ]
