# Generated by Django 4.2.11 on 2024-05-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_academicresources_resources_delete_note_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicResources',
            new_name='AcademicResource',
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
