# Generated by Django 4.2.11 on 2024-05-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_department_school_school_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='studentNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yearOfStudy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
