# Generated by Django 4.2.11 on 2024-05-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_academicresources_academicresource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicresource',
            old_name='ARId',
            new_name='AcademicResourceId',
        ),
    ]
