# Generated by Django 4.2.11 on 2024-05-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_department_userprofile_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
        ),
    ]
