# Generated by Django 4.2.11 on 2024-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_arid_academicresource_academicresourceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicresource',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicresource',
            name='AcademicResourceId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
