# Generated by Django 4.2.11 on 2024-05-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_academicresource_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='ResourceCategory',
        ),
    ]
