# Generated by Django 4.2.11 on 2024-05-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_school_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
