# Generated by Django 4.2.11 on 2024-05-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_department_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='learningInstitution',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learningInstitution',
            field=models.ManyToManyField(related_name='learningInstitution', to='core.institution'),
        ),
    ]
