# Generated by Django 4.2.11 on 2024-05-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_department_school_alter_school_institution_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
