# Generated by Django 4.2.11 on 2024-05-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='institution',
        ),
    ]
