# Generated by Django 5.0.6 on 2024-06-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notesupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='fx_major',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='fx_name',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
